import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/containers/navbar/Navbar";
import { Toaster } from "sonner";

// Font
const FontInter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${FontInter.className} antialiased`}>
        <Navbar />
        {children}
        <Toaster position="top-center"/>
      </body>
    </html>
  );
}